name: Working with Environments
 
on:
     workflow_dispatch: 
         inputs:
             target-env:
                 type: environment
                 default: pre

jobs:
     echo:
         env:
             my-env-value: MY_ENV_VALUE
         environment: ${{inputs.target-env}}
         runs-on: ubuntu-latest
         steps:
             - name: Echo vars
               run: |
                 echo Env variable: $MY_ENV_VALUE